### ISSUE TITLE
mtp proof fails due to wrong arugements

### ISSUE THREAD

**Issue by Sshovon** [0xPolygonID/js-sdk-examples#22]
The following line is trying to verify mtp proof but the arguments (proof, pub_signals) passed into the function are generated earlier for  `AtomicQuerySigV2` which is resulting the validity of the `const mtpProofOk = await proofService.verifyProof(...)= false`. If those arguments are replaced with correct ones things work fine. 
https://github.com/0xPolygonID/js-sdk-examples/blob/469d6fd3d340efff82985b9bfd4c15af30cd2ca7/index.ts#L396
Also, it would be great if the deprecated `publishStateToRHS` is replaced with the correct one `publishRevocationInfoByCredentialStatusType`

**Comment by vmidyllic** [comment]
fixed in #23
