### ISSUE TITLE
Reverse Hash Service URL 404

### ISSUE THREAD

**Issue by gmchad** [0xPolygonID/js-sdk-examples#5]
Looks like https://rhs-staging.polygonid.me/ is giving a 404

**Comment by sanketsaagar** [comment]
Hi @gmchad , If you normally open the link in the browser it will give an error. The RHS URL should be added to the configuration.

**Comment by gmchad** [comment]
@sanketsaagar A 404 is an auth error so unless the config has the auth baked in it will still give a 404.

I tried running the SDK and it indeed returns `AxiosError: Request failed with status code 404`

**Comment by gmchad** [comment]
Fixed - it looks like the code appends `/node` to the URL which does resolve correctly.
